config/routes.rb
Rails.application.routes.draw do

  resources :text_stories
  # get 'home/index'
  root "home#index"
  get "home/audio"
  get "home/text"
  get "home/about"
  get 'home/explore'
  get "text_stories/hindi"
  get "text_stories/english"
  get "stories/akhbar_hindi"
  get "stories/akhbar_english"
  get "stories/rabbit_english"
  get "stories/rabbit_hindi"
  get "stories/swan_hindi"
  get "stories/swan_english"
  get "home/test"

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/text_story.rb
class TextStory < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def audio
  end



  def about
  end

  def explore

  end
  def text
  end
  def test
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def akhbar_hindi
  end

  def akhbar_english
  end

  def rabbit_english
  end

  def rabbit_hindi
  end

  def swan_hindi
  end

  def swan_english
  end

end

app/controllers/text_stories_controller.rb
class TextStoriesController < ApplicationController
  before_action :set_text_story, only: %i[ show edit update destroy ]

  # GET /text_stories or /text_stories.json
  def index
    @text_stories = TextStory.all
  end

  # GET /text_stories/1 or /text_stories/1.json
  def show
  end

  # GET /text_stories/new
  def new
    @text_story = TextStory.new
  end

  # GET /text_stories/1/edit
  def edit
  end
  def english
  end

  def hindi
  end
  # POST /text_stories or /text_stories.json
  def create
    @text_story = TextStory.new(text_story_params)

    respond_to do |format|
      if @text_story.save
        format.html { redirect_to @text_story, notice: "Text story was successfully created." }
        format.json { render :show, status: :created, location: @text_story }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @text_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /text_stories/1 or /text_stories/1.json
  def update
    respond_to do |format|
      if @text_story.update(text_story_params)
        format.html { redirect_to @text_story, notice: "Text story was successfully updated." }
        format.json { render :show, status: :ok, location: @text_story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @text_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_stories/1 or /text_stories/1.json
  def destroy
    @text_story.destroy
    respond_to do |format|
      format.html { redirect_to text_stories_url, notice: "Text story was successfully destroyed." }
      format.json { head :no_content }
    end
  end

   private
    # Use callbacks to share common setup or constraints between actions.
    def set_text_story
   @text_story = TextStory.find(params[:id])
 end

    # Only allow a list of trusted parameters through.
    def text_story_params
      params.require(:text_story).permit(:name_of_story, :description_of_story)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/text_stories_helper.rb
module TextStoriesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <%=link_to "Home", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <%= link_to "Audio stories", home_audio_path, class:"nav-link" %>
      </li>


      <li class="nav-item">
        <%= link_to "Text stories", home_text_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "About US", home_about_path, class:"nav-link" %>
      </li>



    </ul>

  </div>
</nav>

app/views/home/about.html.erb

<div id="about">
  <h1>About us.. </h1>
</div>

app/views/home/explore.html.erb

<html>
<head>
  <style>
      body{
          margin:0px;
          background:#6495ED;

      }
      #main {
          width:100%;
          height:100%;
          position:absolute;
          overflow:hidden;
      }
      #box1 {
          width:530px;
          height:625px;
          background-image:url("https://res.cloudinary.com/davims6ce/image/upload/v1597557706/2_meanqt.png");
          position:absolute;
          bottom:-100%;
          left: 30%;
          animation: anim 2s forwards, anim2 3s forwards 3s;
      }
      #box1:after{
          content:"";
          position:absolute;
          width:530px;
          height:625px;
          background-image:url("https://res.cloudinary.com/davims6ce/image/upload/v1597557706/2_meanqt.png");
          left:0px;
          z-index: -1;

      }

      @keyframes anim {
          from {
              bottom: -100%;
          }
          to {
              bottom:0%;
          }
      }
      @keyframes anim2 {
          from {
              left:30%;
              width:530px;
          }
          to {
              width: 0px;
              left:50%;
          }
      }
      #box2 {
          width: auto;
          height:auto;
          font-family: "Bahnschrift Condensed";
          color:white;
          font-size:8em;
          font-weight:500;
          line-height: 130 px;
          position: absolute;
          top: 250px;
          left: 100px;
          overflow:hidden;

      }
      #text {
          position:relative;
          left:-100%;
          animation: anim3 2s forwards 3s;

      }
      @keyframes anim3 {
          from {
              left:-100%;
          }
          to {
              left:0%;
          }
      }
      #box3 {
          overflow:hidden;
      }
      #container {
          width:100%;
          position:absolute;
          top:100%;
          animation: anim4 2s forwards 2.5s;

      }
      #logo {
          float:left;
          margin-left:100px;
          margin-top:20px;
      }
      #logo img {
          width: 50px;
      }
      @keyframes anim4 {
          from {
              top:-100%;
          }
      }
  </style>
</head>
<body>
<div id="main">
  <div id= "box1"></div>

  <div id="box2">
    <div id="text">
      <%= link_to "Audio", home_audio_path %><br/> <%= link_to "Text", text_stories_path %>
    </div>
  </div>

  <div id="box3">
    <div id="container">
      <div id="logo">
        <img src="https://res.cloudinary.com/davims6ce/image/upload/v1597557707/1_pblr2h.png">
      </div>

      <div id="menu">

      </div>

    </div>
  </div>

</div>
</body>


</html>


app/views/home/index.html.erb
<div style="color:MediumAquaMarine" >

  <body background="https://www.99images.com/download-image/293267/1500x1000">
    <h1> <center>   <font size="+6"> Welcome To Your Story Adventure </font>  </center> </h1>

    <p> <center> <font size="+2"> Click one of the two buttons to get started </font> </center> </p>
    <center> <%= link_to "Audio Stories", home_audio_path, class:"btn btn-info btn-lg "%> <%= link_to "Text Stories", home_text_path, class:"btn btn-info btn-lg "%>   </center>

  </body>
</div>

<div id=" Mission Statement", style="color:MediumAquaMarine">
          <br/><br/><br/> <br/><br/><br/> <br/><br/><br/> <br/><br/><br/> <br/><br/><br/> <br/><br/><br/> <br/><br/><br/>
 <a href="home/about.html"> <center><h3> <strong>Click Here To Learn More about the Webpage </strong> </h3> </center> </a>



</div>

app/views/home/test.html.erb







<script>
var currentFile = “”; //Global variable to track current file
function playAudio() {
// Check for audio element support.
if (window.HTMLAudioElement) {
try {
var oAudio = document.getElementById(‘myaudio’);
var btn = document.getElementById(‘play’);
var audioURL = document.getElementById(‘mylist’); //Skip loading if current file hasn’t changed.
if (audioURL.value !== currentFile) {
oAudio.src = audioURL.value;
currentFile = audioURL.value;
}// Tests the paused attribute and set state.
if (oAudio.paused) {
oAudio.play();
btn.textContent = “Pause”;
}
else {
oAudio.pause();
btn.textContent = “Play”;
}
}
catch (e) {
// Fail silently but show in F12 developer tools console
if(window.console && console.error(“Error:” + e));
}
}
}
</script>

app/views/home/text.html.erb
<style>

    body {
        background: whitesmoke;
    }
</style>
<br/><br/>


<table class="table table-success table-striped table-hover table-bordered">
  <thead>
  <tr>
    <th>Name of story</th>
    <th>Description of story</th>
    <th>  Language </th>

  </tr>
  <tr>
    <td> Akhbar and Birbal:  How Many Turns on the Road</td>
    <td> Akhbar recieves a mysetrious letter from the Emperor of Persia</td>
    <td> <%= link_to "Hindi", stories_akhbar_hindi_path %>   or   <%= link_to "English", stories_akhbar_english_path %></td>
  </tr>
  <tr>
    <td> The Rabbits and the Elephants</td>
    <td> Strength is a testament to one's willpower; Wit can triumph over the mightiest  of foes. </td>
    <td> <%= link_to "Hindi", stories_rabbit_hindi_path %>  or   <%= link_to "English", stories_rabbit_english_path %></td>
  </tr>
  <tr>
    <td> The Golden Swan </td>
    <td> An Abundance of Wealth does not guarantee happiness </td>
    <td> <%= link_to "Hindi", stories_swan_hindi_path %>  or   <%= link_to "English", stories_swan_english_path %> </td>
  </tr>
  </thead>

app/views/stories/akhbar_english.html.erb
<br/>
<div id=" Akhbar Image ">
  <img src="https://upload.wikimedia.org/wikipedia/commons/3/34/Govardhan._Akbar_With_Lion_and_Calf_ca._1630%2C_Metmuseum_%28cropped%29.jpg"
       width="400" height="400" alt="King Akhbar Image">
  <img src="https://artsourceinternational.com/wp-content/uploads/2018/05/MIT-1867-PERSIA.jpg"
       width="400" height="400" alt="Map of Persia">
  <img src="https://static9.depositphotos.com/1526816/1100/v/600/depositphotos_11008008-stock-illustration-house-on-a-hill.jpg"
       width="450" height="400" alt="Map of Persia">
</div>
<div id="story">
  <br/>
  <p>Emperor and Emperor Akbar of Persiawere close friends. They often wrote letters asking each other's well being. In the letter, he also used to write jokes, jokes and riddles. They also used to send gifts to each other when they got the answer of the riddles correct.

    Once a letter from the Emperor of Persia was received by Akbar , in which he had sent a question by writing. The question was something like – “How many turns are there on the roads of your state?”

    After reading the question, Akbar got into thinking. His empire was spread far and wide. The number of roads in such a vast empire was also immense. In such a situation, it was an impossible task to calculate the turns of all the roads.

    But Akbar did not want to be embarrassed in front of the emperor of Persia. He had to answer this question in any case. He called Todarmal and said, "Todarmal! You immediately leave with some soldiers. You have to count the turns of the roads of our entire empire. In any case, let us complete this work." Todarmal left immediately with some soldiers. But even after several days passed, he did not return. Here Akbar started worrying whether Todarmal will be able to do this work or not?

    One day Birbal saw Akbar worried, so he asked, "Jahanpanah! Wow? You seem very worried?

    Akbar told Birbal about the letter of the Emperor of Persia and the question asked in it, "Birbal! We have sent Todarmal to calculate the number of turns of all the roads in the state. We are waiting for him. As well as the concern whether he will return after completing this work or not.

    Knowing the question asked by the emperor of Persia, Birbal smiled and said, "Jahanpanah! You didn't need to send Todermal anywhere for this simple question. I can only tell this standing up that how many turns are there on the roads of your state. Even I can tell how many turns are there in the roads of the whole world. "Birbal! You can tell the number of turns on the roads of our state and the world without counting. how?" Akbar was astonished.

    "Jahanpanah! Because it does not require any calculation. All the roads in the world have only two turns. One right and the other left." Birbal replied calmly.

    Hearing this reply, Akbar laughed, "Oh, we didn't even think about it and sent Todarmal to calculate the turns of the roads. Birbal, you are really intelligent."

    Akbar gave Birbal a gold necklace as a reward and sent him the answer to the question of the emperor of Persia.</p>

</div>
<%= link_to "Back", home_text_path, class:"btn btn-secondary "%>

app/views/stories/akhbar_hindi.html.erb
<br/>
<div id=" Akhbar Image ">
  <img src="https://upload.wikimedia.org/wikipedia/commons/3/34/Govardhan._Akbar_With_Lion_and_Calf_ca._1630%2C_Metmuseum_%28cropped%29.jpg"
       width="400" height="400" alt="King Akhbar Image">
  <img src="https://artsourceinternational.com/wp-content/uploads/2018/05/MIT-1867-PERSIA.jpg"
       width="400" height="400" alt="Map of Persia">
  <img src="https://static9.depositphotos.com/1526816/1100/v/600/depositphotos_11008008-stock-illustration-house-on-a-hill.jpg"
       width="450" height="400" alt="Map of Persia">
</div>
<div id="story">
  <br/>
  <p>"फ़ारस के शहंशाह और बादशाह अकबर गहरे मित्र थे. अक्सर पत्र लिखकर वे एक-दूसरे का हाल-चाल पूछते रहते थे. पत्र में वे आमोद-प्रमोद की बातें, लतीफ़े और पहेलियाँ भी लिखते थे. पहेलियों का उत्तर सही मिलने पर वे एक-दूसरे को उपहार भी भेजा करते थे.

एक बार फ़ारस के शहंशाह का पत्र अकबर (Akbar) को प्राप्त हुआ, जिसमें उन्होंने एक प्रश्न लिखकर प्रेषित किया था. प्रश्न कुछ ऐसा था – “आपके राज्य की सड़कों पर कितने मोड़ हैं?”

प्रश्न पढ़कर अकबर (Akbar) सोच में पड़ गए. उनका सम्राज्य दूर-दूर तक फैला हुआ था. इतने विस्तृत साम्राज्य में सड़कों की संख्या भी अत्यधिक थी. ऐसे में सभी सड़कों के मोड़ों की गणना कर पाना एक नामुमकिन कार्य था.

लेकिन अकबर फ़ारस के शहंशाह के सामने शर्मिंदा नहीं होना चाहते थे. उन्हें किसी भी सूरत में इस प्रश्न का उत्तर देना ही था. उन्होंने टोडरमल को बुलवाया और कहा, “टोडरमल! तुम अभी तुरंत कुछ सैनिकों को लेकर निकल जाओ. तुम्हें हमारे पूरे साम्राज्य की सड़कों के मोड़ों की गणना करनी है. किसी भी सूरत में हमें ये काम पूरा करके दो.” टोडरमल कुछ सैनिकों को लेकर तुरंत निकल गया. लेकिन कई दिन बीत जाने के बाद भी नहीं लौटा. इधर अकबर को चिंता सताने लगी कि ये कार्य टोडरमल कर पायेगा भी या नहीं?

एक दिन बीरबल ने अकबर को चिंतित देखा, तो पूछ बैठा, “जहाँपनाह! क्या बात है? आप बड़े चिंतित लग रहे हैं?

अकबर ने फ़ारस के शहंशाह के पत्र और उसमें पूछे गए प्रश्न के बारे में बीरबल को बताते हुए कहा, “बीरबल! हमने टोडरमल को राज्य की सभी सड़कों के मोड़ों की संख्या की गणना के लिए भेजा है. हमें उसकी ही प्रतीक्षा है. साथ ही ये चिंता भी कि वो ये काम पूरा करके लौटेंगा या नहीं.”

फ़ारस के शहंशाह के पूछे गए प्रश्न को जानकर बीरबल मुस्कुरा उठा और बोला, “जहाँपनाह! इस आसान से प्रश्न के लिए आपको टोडरमल को कहीं भी भेजने की आवश्यकता नहीं थी. मैं तो यही खड़े-खड़े ये बता सकता हूँ कि आपके राज्य की सड़कों पर कितने मोड़ हैं. यहाँ तक कि मैं तो ये भी बता सकता हूँ कि पूरी दुनिया की सड़कों में कितने मोड़ हैं.” “बीरबल! तुम बिना गणना किये हमारे राज्य और दुनिया की सड़कों के मोड़ों की संख्या बता सकते हो. कैसे?” अकबर हैरत में पड़ गए.

“जहाँपनाह! क्योंकि इसमें गणना की आवश्यकता ही नहीं है. दुनिया की सारी सड़कों के बस दो ही तो मोड़ होते हैं. एक दांया और दूसरा बांया.” बीरबल (birbal) ने शांतभाव से उत्तर दिया.

ये उत्तर सुनकर अकबर हँस पड़े, “अरे, हमने तो ये सोचा ही नहीं और टोडरमल को सड़कों के मोड़ों की गणना के लिए भेज दिया. बीरबल तुम वाकई अक्लमंद हो.”

    अकबर ने बीरबल को इनाम में सोने का हार दिया और फ़ारस के शहंशाह के प्रश्न का उत्तर उन्हें भिजवा दिया.</p>
</div>
<%= link_to "Back", home_text_path, class:"btn btn-secondary "%>

app/views/stories/rabbit_english.html.erb
<br/>
<div id=" Story Image ">
  <center><img src="https://cdn2.momjunction.com/wp-content/uploads/2014/06/Elephants-And-Hares.jpg"
               alt="rabbit and elephant image"> </center>

</div>
<div id="story">
  <br/>
  <p>  Once upon a time, there lived a herd of Elephants in a forest. A mighty Elephant by the name of Chaturdanta was their king. There was a big lake in the middle of the forest where all the animals used to go to drink water and to take a bath. Once it so happened, that there was no rain for the whole year and the lake dried up. Many of the birds and the animals died of thirst. The Elephants got worried that if they didn’t get water soon many of them would die of thirst.

    The Elephants decided to take the matter to their king, Chaturdanta. So they approached their king and said, “You Majesty, as you know there is no water in our forest, many of the birds and animals have died due to thirst. We require water in order to survive. If we will stay here soon many of us will die. We have to find out water as soon as possible”. The King Elephant considered the idea and asked the Elephants to go in different directions to find water. Fortunately, one of them found a large lake full of water in another jungle far away.

    The King Elephant got happy to hear this news. He ordered all his followers to make their way towards the lake. This lake was full of water and never went dry even if it didn’t rain. On the way to this lake, there was a settlement of Rabbits. The Elephants had to pass through this settlement of Rabbits. Thousands of Rabbit got crushed under the heavy feet of the Elephants and many of them got wounded. The Rabbits fled in terror. The situation was getting severe, so the King of the Rabbits called up a meeting.

    In the meeting, the King said,” A herd of Elephants is passing through our area. They have killed thousands of our friends. We are in a critical need to avoid more deaths. I want all of you to think of a way to save our race”. All the Rabbits underwent a thought process. Suddenly, a little Rabbit derived a plan and said to the King, “Your Majesty, if you will send me as your messenger to the King of the Elephants, I might find a solution to this problem”. The Rabbit King gave his approval to the idea. The little Rabbit rushed towards the lake.

    When he saw the herd of Elephants returning from the lake, he realized that it was impossible to get near to them. Then he thought that how could he talk to the King of Elephants. Thus, he climbed up a hill and shouted, “O, King of the Elephants. Please listen to me”. On hearing the Rabbit’s voice, Chaturdanta stopped for a while and replied,” Who are you? From where have you come?” The smart Rabbit answered, “I am a messenger sent to you by the Moon God”. The King of the Elephants said, “Why you have come here?”

    The Rabbit replied, “Moon God has sent a message for you. A messenger speaks only truth. Please consider that a messenger is never punished for what he has to say. He is only doing his job so you must not be angry with me”. Chaturdanta confirmed him that he won’t be harmed in any way. The little Rabbit said, “The Moon God is angry with you because you have brought your herd to his holy lake and have disturbed the peace. You have crushed thousands of Rabbits to death on the way to lake. Rabbits are under the special protection of Moon God. Since you have bothered the Moon God and his special creatures, he is extremely annoyed with you and wants you to leave his kingdom at once. If not, then you might face terrible consequences”.

    The King Elephant was scared to hear this message from the Moon God. He said, “You are right. We have killed many rabbits on our way to the lake. But really that was done in ignorance. I will see that you do not suffer anymore. I want to request the Moon God to pardon me for my sins. Please advise me what I should do”. The Rabbit replied, “Ok. I will take you to the Moon God. Pay your homage to the God and ask him to forgive you for the crime you have committed. Come with me”.

    At night, the Rabbit led the King of Elephants to the lake. Both, the Rabbit and the Elephant stood near the bank of the lake. There they saw the reflected image of the Moon in the still water. Just then, a mild breeze blew disturbing the waters of the lake and the moon seemed to move to and fro. When Chaturdanta saw this, he thought that the Moon God was really angry with him. He bowed to the Moon God in panic. The Rabbit said, “Oh Moon God, The King of Elephants has done a sin in ignorance. Please forgive him. He is taking away his herd from here and promising never to come back”.

    Frightened Chaturdanta bowed once again to the Moon God and left the place with his herd immediately. And the Rabbits lived happily in their settlement ever after. </p>

</div>
<%= link_to "Back", home_text_path, class:"btn btn-secondary "%>

app/views/stories/swan_english.html.erb
<br/>
<div id=" Swan Image ">
  <center><img src="https://www.culturalindia.net/iliimages/The-Golden-Swan-ili-288-ogimg.jpg"> </center>
</div>
<div id="story">
  <br/>
  <p>Once upon a time, there was a swan that had striking golden feathers. This swan lived in a pond. There was a house near this pond, where a poor woman lived with her two daughters. The people were really poor and were leading a tough life. The swan found that the poor mother was passing a hard time with her daughters.

    The swan thought, “If I give them one after another my golden feathers, the mother can sell them. She and her daughters can live in comfort with the money raised from it”. After thinking this, the swan flew away to the poor woman’s house. On seeing the swan inside the house, the woman said,” Why have you come here? We have nothing to offer you”.

    The Swan replied, “I have not come to take anything, but I have something to give you. I know your condition. I will give my golden feathers one by one and you can sell them. With the money raised through it, you people can easily live in comfort”. After saying this, the swan shed one of her feathers and then flew away. This became a regular feature and from time to time, the swan came back and every time left another feather.

    Like this, the mother and her daughters were happily leading their life by selling the feathers of the golden swan. Each golden feather got them enough money to keep them in comfort. But the mother became greedy to get all the feathers as soon as possible. One day, she said to her daughters, “Now, we will not trust this swan, possibly she may fly away and never come back. If this would happen, we will be poor again. We will take all of her feathers, when she will come the next time”.

    The innocent daughters replied, “Mother, this will hurt the swan. We will not cause any pain to her”. But the mother was determined to catch hold the swan the very next time she comes. Next time, when the swan came, the mother caught her and pulled out all of her feathers. Now, the golden feathers of the swan changed into some strange feathers. The mother was shocked to see such feathers.

    The Golden Swan said, “Poor Mother, I wanted to help you, but you wanted to kill me instead. As per my wish, I used to give you the golden feather. Now, I think there is no need to help you. Now, my feathers are nothing more than chicken feathers for you. I am going from this place and will never come back”. The mother felt sorry and apologized for the mistake committed by her. The Golden Swan said, “Never be greedy” and flew away.</p>

</div>
<%= link_to "Back", home_text_path, class:"btn btn-secondary "%>

app/views/text_stories/edit.html.erb
<h1>Editing Text Story</h1>

<%= render 'form', text_story: @text_story %>

<%= link_to 'Show', @text_story %> |
<%= link_to 'Back', text_stories_path %>

app/views/text_stories/index.html.erb
<style>

    body {
        background: white;
    }
</style>


<p id="notice"><%= notice %></p>

<h1>Text Stories</h1>

<table class="table table-success table-striped table-hover">
  <thead>
    <tr>
      <th>Name of story</th>
      <th>Description of story</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @text_stories.each do |text_story| %>
      <tr>
        <td><%= text_story.name_of_story %></td>
        <td><%= text_story.description_of_story %></td>
        <td><%= link_to 'Show', text_story %></td>

        <!--
        <td><%= link_to 'Edit', edit_text_story_path(text_story) %></td>
        <td><%= link_to 'Destroy', text_story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!--
<%= link_to 'New Text Story', new_text_story_path %>
-->

app/views/text_stories/new.html.erb
<h1>New Text Story</h1>

<%= render 'form', text_story: @text_story %>

<%= link_to 'Back', text_stories_path %>

app/views/text_stories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4"><%= @text_story.name_of_story %> </h1>
  <p class="lead"><%= @text_story.description_of_story %></p>
  <p class="lead">
    <a class="btn btn-secondary" href="#" role="button"> Hindi </a>
    <a class="btn btn-secondary" href="#" role="button">English </a>
  </p>
  <hr class="my-4">


</div>






<!--
<%= link_to 'Edit', edit_text_story_path(@text_story) %> |
-->
<%= link_to 'Back', text_stories_path, class:"btn btn-secondary" %>